/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author mjper
 */
public class Lab6 extends javax.swing.JFrame {

    /**
     * Creates new form Lab6
     */
    public Lab6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_jugador = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_nombrej = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_precio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_posicion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        rb_disponibilidad = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tf_habilidad = new javax.swing.JTextField();
        tf_tecnica = new javax.swing.JTextField();
        tf_resistencia = new javax.swing.JTextField();
        jd_equipo = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_nombree = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_presupuesto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_estadio = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        tf_copas = new javax.swing.JTextField();
        jd_listar = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_jugadores = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_equipos = new javax.swing.JList<>();
        jButton5 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        ppm_modelij = new javax.swing.JPopupMenu();
        jmi_eliminarj = new javax.swing.JMenuItem();
        jmi_modificarj = new javax.swing.JMenuItem();
        jd_jugadormod = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        tf_nombrej1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tf_precio1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tf_posicion1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        rb_disponibilidad1 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        tf_habilidad1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tf_tecnica1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tf_resistencia1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        ppm_modelie = new javax.swing.JPopupMenu();
        jmi_eliminare = new javax.swing.JMenuItem();
        jmi_modificare = new javax.swing.JMenuItem();
        jd_equipomod = new javax.swing.JDialog();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tf_nombree1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        tf_presupuesto1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        tf_estadio1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        tf_copas1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jd_arbol = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_arbol = new javax.swing.JTree();
        jLabel34 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        ppm_arbol = new javax.swing.JPopupMenu();
        jmi_datos = new javax.swing.JMenuItem();
        jmi_cambios = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmi_modeli = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("Jugador");

        jLabel3.setText("Nombre");

        tf_nombrej.setText(" ");

        jLabel4.setText("Precio");

        tf_precio.setText(" ");

        jLabel5.setText("Posicion");

        tf_posicion.setText(" ");

        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Disponibilidad");

        rb_disponibilidad.setText("Click si no esta disponible");

        jLabel15.setText("Habilidad");

        jLabel16.setText("Tecnica");

        jLabel17.setText("Resistencia Fisica");

        tf_habilidad.setText(" ");

        tf_tecnica.setText(" ");

        tf_resistencia.setText(" ");

        javax.swing.GroupLayout jd_jugadorLayout = new javax.swing.GroupLayout(jd_jugador.getContentPane());
        jd_jugador.getContentPane().setLayout(jd_jugadorLayout);
        jd_jugadorLayout.setHorizontalGroup(
            jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_jugadorLayout.createSequentialGroup()
                .addGap(0, 384, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(348, 348, 348))
            .addGroup(jd_jugadorLayout.createSequentialGroup()
                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_jugadorLayout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(jButton1))
                    .addGroup(jd_jugadorLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_jugadorLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(rb_disponibilidad))
                            .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jd_jugadorLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jd_jugadorLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jd_jugadorLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(46, 46, 46)
                                    .addComponent(tf_nombrej, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_jugadorLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(tf_resistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_jugadorLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(44, 44, 44)
                                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_habilidad)
                                    .addGroup(jd_jugadorLayout.createSequentialGroup()
                                        .addComponent(tf_tecnica, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_jugadorLayout.setVerticalGroup(
            jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_jugadorLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_nombrej, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(rb_disponibilidad))
                .addGap(39, 39, 39)
                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_habilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_tecnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_resistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setText("Equipo");

        jLabel7.setText("Nombre");

        jLabel8.setText("Presupuesto");

        tf_presupuesto.setText(" ");
        tf_presupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_presupuestoActionPerformed(evt);
            }
        });

        jLabel9.setText("Estadio");

        jButton2.setText("Agregar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel18.setText("Copas ganadas");

        tf_copas.setText(" ");

        javax.swing.GroupLayout jd_equipoLayout = new javax.swing.GroupLayout(jd_equipo.getContentPane());
        jd_equipo.getContentPane().setLayout(jd_equipoLayout);
        jd_equipoLayout.setHorizontalGroup(
            jd_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_equipoLayout.createSequentialGroup()
                .addGroup(jd_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_equipoLayout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addGroup(jd_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_equipoLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jd_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_equipoLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(36, 36, 36)
                                .addComponent(tf_copas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_equipoLayout.createSequentialGroup()
                                .addGroup(jd_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(38, 38, 38)
                                .addGroup(jd_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_estadio)
                                    .addComponent(tf_presupuesto, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(tf_nombree))))))
                .addContainerGap(397, Short.MAX_VALUE))
        );
        jd_equipoLayout.setVerticalGroup(
            jd_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_equipoLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel6)
                .addGap(83, 83, 83)
                .addGroup(jd_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_nombree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jd_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_presupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jd_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_estadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(52, 52, 52)
                .addGroup(jd_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_copas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(76, 76, 76))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel10.setText("Comprar jugadores y Listar");

        jLabel11.setText("Jugadores");

        jLabel12.setText("NOmbre  COpas");

        jl_jugadores.setModel(new DefaultListModel());
        jl_jugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_jugadoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_jugadores);

        jl_equipos.setModel(new DefaultListModel());
        jl_equipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_equiposMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_equipos);

        jButton5.setText("Comprar jugador");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jLabel31.setText("Elija el equipo que compra y el jugador a comprar");

        jLabel32.setText("Click derecho para eliminar y modificar");

        jLabel33.setText("Nombre   Precio  Posicion  Disponibilidad ");

        jLabel36.setText("Equipo");

        javax.swing.GroupLayout jd_listarLayout = new javax.swing.GroupLayout(jd_listar.getContentPane());
        jd_listar.getContentPane().setLayout(jd_listarLayout);
        jd_listarLayout.setHorizontalGroup(
            jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
            .addGroup(jd_listarLayout.createSequentialGroup()
                .addGroup(jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_listarLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel11))
                    .addGroup(jd_listarLayout.createSequentialGroup()
                        .addGroup(jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_listarLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_listarLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel33)))
                        .addGroup(jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_listarLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_listarLayout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addGroup(jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel12)))))
                    .addGroup(jd_listarLayout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_listarLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel31))
                    .addGroup(jd_listarLayout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(jLabel32)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jd_listarLayout.setVerticalGroup(
            jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel32)
                .addGroup(jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_listarLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel36)))
                .addGroup(jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_listarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(jd_listarLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jmi_eliminarj.setText("Eliminar");
        jmi_eliminarj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarjActionPerformed(evt);
            }
        });
        ppm_modelij.add(jmi_eliminarj);

        jmi_modificarj.setText("Modificar");
        jmi_modificarj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_modificarjActionPerformed(evt);
            }
        });
        ppm_modelij.add(jmi_modificarj);

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel13.setText("Modificar Jugador");

        tf_nombrej1.setText(" ");

        jLabel19.setText("Nombre");

        jLabel20.setText("Precio");

        tf_precio1.setText(" ");

        jLabel21.setText("Posicion");

        tf_posicion1.setText(" ");

        jLabel22.setText("Disponibilidad");

        rb_disponibilidad1.setText("Click si no esta disponible");

        jLabel23.setText("Habilidad");

        tf_habilidad1.setText(" ");

        jLabel24.setText("Tecnica");

        tf_tecnica1.setText(" ");

        jLabel25.setText("Resistencia Fisica");

        tf_resistencia1.setText(" ");

        jButton4.setText("Modificar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_jugadormodLayout = new javax.swing.GroupLayout(jd_jugadormod.getContentPane());
        jd_jugadormod.getContentPane().setLayout(jd_jugadormodLayout);
        jd_jugadormodLayout.setHorizontalGroup(
            jd_jugadormodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_jugadormodLayout.createSequentialGroup()
                .addGroup(jd_jugadormodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_jugadormodLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jd_jugadormodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_jugadormodLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(rb_disponibilidad1))
                            .addGroup(jd_jugadormodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jd_jugadormodLayout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_posicion1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jd_jugadormodLayout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_precio1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jd_jugadormodLayout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addGap(46, 46, 46)
                                    .addComponent(tf_nombrej1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_jugadormodLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(tf_resistencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_jugadormodLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jd_jugadormodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addGap(44, 44, 44)
                                .addGroup(jd_jugadormodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_habilidad1)
                                    .addGroup(jd_jugadormodLayout.createSequentialGroup()
                                        .addComponent(tf_tecnica1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jd_jugadormodLayout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_jugadormodLayout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(jButton4)))
                .addContainerGap(376, Short.MAX_VALUE))
        );
        jd_jugadormodLayout.setVerticalGroup(
            jd_jugadormodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_jugadormodLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel13)
                .addGap(49, 49, 49)
                .addGroup(jd_jugadormodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tf_nombrej1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jd_jugadormodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_precio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jd_jugadormodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_posicion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jd_jugadormodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(rb_disponibilidad1))
                .addGap(39, 39, 39)
                .addGroup(jd_jugadormodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tf_habilidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jd_jugadormodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tf_tecnica1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jd_jugadormodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tf_resistencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(79, 79, 79))
        );

        jmi_eliminare.setText("Eliminar");
        jmi_eliminare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminareActionPerformed(evt);
            }
        });
        ppm_modelie.add(jmi_eliminare);

        jmi_modificare.setText("Modificar");
        jmi_modificare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_modificareActionPerformed(evt);
            }
        });
        ppm_modelie.add(jmi_modificare);

        jLabel26.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel26.setText("Equipo");

        jLabel27.setText("Nombre");

        jLabel28.setText("Presupuesto");

        tf_presupuesto1.setText(" ");
        tf_presupuesto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_presupuesto1ActionPerformed(evt);
            }
        });

        jLabel29.setText("Estadio");

        jLabel30.setText("Copas ganadas");

        tf_copas1.setText(" ");

        jButton3.setText("Modificar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_equipomodLayout = new javax.swing.GroupLayout(jd_equipomod.getContentPane());
        jd_equipomod.getContentPane().setLayout(jd_equipomodLayout);
        jd_equipomodLayout.setHorizontalGroup(
            jd_equipomodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_equipomodLayout.createSequentialGroup()
                .addGroup(jd_equipomodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_equipomodLayout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addGroup(jd_equipomodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_equipomodLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jd_equipomodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_equipomodLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(36, 36, 36)
                                .addComponent(tf_copas1))
                            .addGroup(jd_equipomodLayout.createSequentialGroup()
                                .addGroup(jd_equipomodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(38, 38, 38)
                                .addGroup(jd_equipomodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_nombree1)
                                    .addComponent(tf_presupuesto1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(tf_estadio1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(397, Short.MAX_VALUE))
        );
        jd_equipomodLayout.setVerticalGroup(
            jd_equipomodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_equipomodLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel26)
                .addGap(83, 83, 83)
                .addGroup(jd_equipomodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tf_nombree1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jd_equipomodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tf_presupuesto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jd_equipomodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_estadio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(52, 52, 52)
                .addGroup(jd_equipomodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tf_copas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(76, 76, 76))
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Liga Española");
        jt_arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_arbolMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jt_arbol);

        jLabel34.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel34.setText("Arbol");

        jButton6.setText("Actualizar arbol");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_arbolLayout = new javax.swing.GroupLayout(jd_arbol.getContentPane());
        jd_arbol.getContentPane().setLayout(jd_arbolLayout);
        jd_arbolLayout.setHorizontalGroup(
            jd_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_arbolLayout.createSequentialGroup()
                .addGroup(jd_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_arbolLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_arbolLayout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addGroup(jd_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jd_arbolLayout.setVerticalGroup(
            jd_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_arbolLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        jmi_datos.setText("Datos");
        jmi_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_datosActionPerformed(evt);
            }
        });
        ppm_arbol.add(jmi_datos);

        jmi_cambios.setText("Sacarjugador");
        jmi_cambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cambiosActionPerformed(evt);
            }
        });
        ppm_arbol.add(jmi_cambios);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Inicio");

        jLabel35.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel35.setText("Liga española programa");

        jMenu1.setText("Agregar");

        jMenuItem2.setText("Jugador");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Equipo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Comprar y Listar");

        jmi_modeli.setText("Comprar, Modificar y Eliminar");
        jmi_modeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_modeliActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_modeli);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Arbol");

        jMenuItem3.setText("Abrir Arbol");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

        //String nombre, String posicion, String disponibilidad, String habilidad, String tecnica, String resistencia, double precio
        boolean disponibilidad;

        if (rb_disponibilidad.isSelected()) {
            disponibilidad = false;
        } else {
            disponibilidad = true;
        }

        Jugador j = new Jugador(tf_nombrej.getText(), tf_posicion.getText(),
                disponibilidad, tf_habilidad.getText(), tf_tecnica.getText(), tf_resistencia.getText(), Double.parseDouble(tf_precio.getText()));

        tf_nombrej.setText("");
        tf_posicion.setText("");
        rb_disponibilidad.setSelected(false);
        tf_habilidad.setText("");
        tf_tecnica.setText("");
        tf_resistencia.setText("");
        tf_precio.setText("");
        DefaultListModel modelo = (DefaultListModel) jl_jugadores.getModel();
        modelo.addElement(j);

        listjugadores.add(j);

        JOptionPane.showMessageDialog(this, "Ha sido agregado con exito");

    }//GEN-LAST:event_jButton1MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.jd_jugador.setModal(true);
        jd_jugador.pack();
        jd_jugador.setLocationRelativeTo(this);
        jd_jugador.setVisible(true);


    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void tf_presupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_presupuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_presupuestoActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        //String nombre, String numero_copas, String estadio, double presupuesto
        Equipo eq = new Equipo(tf_nombree.getText(), (String) tf_copas.getText(), tf_estadio.getText(), Double.parseDouble(tf_presupuesto.getText()));
        DefaultListModel modelo = (DefaultListModel) jl_equipos.getModel();
        modelo.addElement(eq);
        listaequipo.add(eq);

        tf_nombree.setText("");
        tf_copas.setText("");
        tf_estadio.setText("");
        tf_presupuesto.setText("");
        DefaultTreeModel m = (DefaultTreeModel) jt_arbol.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();

        DefaultMutableTreeNode nodo_equipo;

        nodo_equipo = new DefaultMutableTreeNode(eq);

        raiz.add(nodo_equipo);
        m.reload();

        JOptionPane.showMessageDialog(this, "Ha sido agregado con exito");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        this.jd_equipo.setModal(true);
        jd_equipo.pack();
        jd_equipo.setLocationRelativeTo(this);
        jd_equipo.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmi_modeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_modeliActionPerformed
        // TODO add your handling code here:
        this.jd_listar.setModal(true);
        jd_listar.pack();
        jd_listar.setLocationRelativeTo(this);
        jd_listar.setVisible(true);

    }//GEN-LAST:event_jmi_modeliActionPerformed

    private void jl_jugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_jugadoresMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            ppm_modelij.show(evt.getComponent(), evt.getX(), evt.getY());

        }//Fin if


    }//GEN-LAST:event_jl_jugadoresMouseClicked

    private void jmi_eliminarjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarjActionPerformed
        // TODO add your handling code here:

        DefaultListModel modelo = (DefaultListModel) jl_jugadores.getModel();
        modelo.remove(jl_jugadores.getSelectedIndex());


    }//GEN-LAST:event_jmi_eliminarjActionPerformed

    private void jmi_modificarjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_modificarjActionPerformed
        // TODO add your handling code here:

        this.jd_jugadormod.setModal(true);
        jd_jugadormod.pack();
        jd_jugadormod.setLocationRelativeTo(this);
        jd_jugadormod.setVisible(true);


    }//GEN-LAST:event_jmi_modificarjActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        boolean disponibilidad;
        ((Jugador) jl_jugadores.getSelectedValue()).setNombre(tf_nombrej1.getText());
        if (rb_disponibilidad1.isSelected()) {
            disponibilidad = false;
        } else {
            disponibilidad = true;
        }

        ((Jugador) jl_jugadores.getSelectedValue()).setDisponibilidad(disponibilidad);
        ((Jugador) jl_jugadores.getSelectedValue()).setHabilidad(tf_habilidad1.getText());
        ((Jugador) jl_jugadores.getSelectedValue()).setPosicion(tf_posicion1.getText());
        ((Jugador) jl_jugadores.getSelectedValue()).setPrecio(Double.parseDouble(tf_precio1.getText()));
        ((Jugador) jl_jugadores.getSelectedValue()).setResistencia(tf_resistencia1.getText());
        ((Jugador) jl_jugadores.getSelectedValue()).setTecnica(tf_tecnica1.getText());

        JOptionPane.showMessageDialog(this, "Ha sido modificado  con exito");


    }//GEN-LAST:event_jButton4MouseClicked

    private void jmi_eliminareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminareActionPerformed
        // TODO add your handling code here:

        DefaultListModel modelo = (DefaultListModel) jl_equipos.getModel();
        modelo.remove(jl_equipos.getSelectedIndex());


    }//GEN-LAST:event_jmi_eliminareActionPerformed

    private void jl_equiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_equiposMouseClicked
        // TODO add your handling code here:

        if (evt.isMetaDown()) {
            ppm_modelie.show(evt.getComponent(), evt.getX(), evt.getY());

        }//Fin if
    }//GEN-LAST:event_jl_equiposMouseClicked

    private void tf_presupuesto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_presupuesto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_presupuesto1ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        ((Equipo) jl_equipos.getSelectedValue()).setEstadio(tf_estadio1.getText());
        ((Equipo) jl_equipos.getSelectedValue()).setNombre(tf_nombree1.getText());
        ((Equipo) jl_equipos.getSelectedValue()).setNumero_copas(tf_copas1.getText());
        ((Equipo) jl_equipos.getSelectedValue()).setPresupuesto(Double.parseDouble(tf_presupuesto1.getText()));

        JOptionPane.showMessageDialog(this, "Ha sido modificado con exito con exito");

    }//GEN-LAST:event_jButton3MouseClicked

    private void jmi_modificareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_modificareActionPerformed
        // TODO add your handling code here:
        this.jd_equipomod.setModal(true);
        jd_equipomod.pack();
        jd_equipomod.setLocationRelativeTo(this);
        jd_equipomod.setVisible(true);
    }//GEN-LAST:event_jmi_modificareActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:

        boolean aux = jl_jugadores.getSelectedValue().getDisponibilidad();

        if (aux && (jl_equipos.getSelectedValue().getPresupuesto() > jl_jugadores.getSelectedValue().getPrecio())) {

            jl_jugadores.getSelectedValue().setDisponibilidad(false);
            jl_equipos.getSelectedValue().setPresupuesto(jl_equipos.getSelectedValue().getPresupuesto() - jl_jugadores.getSelectedValue().getPrecio());
            //Agregar al equipo
            System.out.println(jl_equipos.getSelectedValue());
            jl_equipos.getSelectedValue().getListajugador().add(jl_jugadores.getSelectedValue());

            DefaultTreeModel m = (DefaultTreeModel) jt_arbol.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();

            // raiz.removeAllChildren();
            DefaultMutableTreeNode equipo = new DefaultMutableTreeNode(jl_equipos.getSelectedValue());
            DefaultMutableTreeNode jugador = new DefaultMutableTreeNode(jl_jugadores.getSelectedValue().getNombre()+"("+jl_jugadores.getSelectedValue().getPosicion()+")");

            equipo.add(jugador);
            raiz.add(equipo);

            m.reload();

            JOptionPane.showMessageDialog(jd_listar, "Se hizo la compra");

        } else {
            JOptionPane.showMessageDialog(jd_listar, "No se puede hacer la compra");
        }


    }//GEN-LAST:event_jButton5MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.jd_arbol.setModal(true);
        jd_arbol.pack();
        jd_arbol.setLocationRelativeTo(this);
        jd_arbol.setVisible(true);


    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jt_arbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_arbolMouseClicked
        // TODO add your handling code here:
        
        
        if(evt.isMetaDown()){
            
            //Seleccionar el nodo con click derecho
            int row= jt_arbol.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_arbol.setSelectionRow(row);
            
            //Determinar el tipo de objeto
            //COntenido en e objeto seleccionado
            //1. Determinar cual esta seleccionado
            
            Object v1 = jt_arbol.getSelectionPath().getLastPathComponent();
            nodo_seleccionado= (DefaultMutableTreeNode)v1;
            
            if(nodo_seleccionado.getUserObject() instanceof Jugador){
                jugador_seleccionado= (Jugador) nodo_seleccionado.getUserObject();
                ppm_arbol.show(evt.getComponent(),evt.getX(),evt.getY());
            }
            
            
            
            /*this.ppmenu.show(evt.getComponent(), evt.getX(), evt.getY());ppeliminararbol*/
        }
    }//GEN-LAST:event_jt_arbolMouseClicked

    private void jmi_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_datosActionPerformed
        // TODO add your handling code here:
        
        String datos;
        
        Jugador selec =(Jugador) nodo_seleccionado.getUserObject();
        
        datos= selec.getNombre()+"\n"+selec.getHabilidad()+"\n"+"\n"+selec.getPosicion()+"\n"+selec.getResistencia()+"\n"+selec.getTecnica();
        JOptionPane.showMessageDialog(jd_arbol, datos);
               
        
        
        
    }//GEN-LAST:event_jmi_datosActionPerformed

    private void jmi_cambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cambiosActionPerformed
        // TODO add your handling code here:
        
        Jugador selec =(Jugador) nodo_seleccionado.getUserObject();
        
        selec.setDisponibilidad(true);
        
        JOptionPane.showMessageDialog(jd_arbol, "Jugador eliminado con exito");
        
        
        
        
        
    }//GEN-LAST:event_jmi_cambiosActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:

        DefaultTreeModel m = (DefaultTreeModel) jt_arbol.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();

        //equipo= new DefaultMutableTreeNode()
    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog jd_arbol;
    private javax.swing.JDialog jd_equipo;
    private javax.swing.JDialog jd_equipomod;
    private javax.swing.JDialog jd_jugador;
    private javax.swing.JDialog jd_jugadormod;
    private javax.swing.JDialog jd_listar;
    private javax.swing.JList<Equipo> jl_equipos;
    private javax.swing.JList<Jugador> jl_jugadores;
    private javax.swing.JMenuItem jmi_cambios;
    private javax.swing.JMenuItem jmi_datos;
    private javax.swing.JMenuItem jmi_eliminare;
    private javax.swing.JMenuItem jmi_eliminarj;
    private javax.swing.JMenuItem jmi_modeli;
    private javax.swing.JMenuItem jmi_modificare;
    private javax.swing.JMenuItem jmi_modificarj;
    private javax.swing.JTree jt_arbol;
    private javax.swing.JPopupMenu ppm_arbol;
    private javax.swing.JPopupMenu ppm_modelie;
    private javax.swing.JPopupMenu ppm_modelij;
    private javax.swing.JRadioButton rb_disponibilidad;
    private javax.swing.JRadioButton rb_disponibilidad1;
    private javax.swing.JTextField tf_copas;
    private javax.swing.JTextField tf_copas1;
    private javax.swing.JTextField tf_estadio;
    private javax.swing.JTextField tf_estadio1;
    private javax.swing.JTextField tf_habilidad;
    private javax.swing.JTextField tf_habilidad1;
    private javax.swing.JTextField tf_nombree;
    private javax.swing.JTextField tf_nombree1;
    private javax.swing.JTextField tf_nombrej;
    private javax.swing.JTextField tf_nombrej1;
    private javax.swing.JTextField tf_posicion;
    private javax.swing.JTextField tf_posicion1;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_precio1;
    private javax.swing.JTextField tf_presupuesto;
    private javax.swing.JTextField tf_presupuesto1;
    private javax.swing.JTextField tf_resistencia;
    private javax.swing.JTextField tf_resistencia1;
    private javax.swing.JTextField tf_tecnica;
    private javax.swing.JTextField tf_tecnica1;
    // End of variables declaration//GEN-END:variables
ArrayList<Jugador> listjugadores = new ArrayList();
    ArrayList<Equipo> listaequipo = new ArrayList();
    DefaultMutableTreeNode nodo_seleccionado;
Jugador jugador_seleccionado;
}
