/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mjper
 */
public class Principal_Examen extends javax.swing.JFrame {

    /**
     * Creates new form Principal_Examen
     */
    public Principal_Examen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        nombre_login = new javax.swing.JTextField();
        contra_login = new javax.swing.JTextField();
        boton_entrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_edad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_sexo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_estadocivil = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        rb_familiar = new javax.swing.JRadioButton();
        rb_personal = new javax.swing.JRadioButton();
        jLabel36 = new javax.swing.JLabel();
        tf_contraseña = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cob_personas = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_nombre1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_edad1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_id1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_sexo1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tf_estadocivil1 = new javax.swing.JTextField();
        rb_familiar1 = new javax.swing.JRadioButton();
        rb_personal1 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bot_modificar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cb_personas2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_personas = new javax.swing.JTable();
        cob_eliminar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        comb_dueño = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        bt_agregarobjeto = new javax.swing.JButton();
        rad_ropa = new javax.swing.JRadioButton();
        rad_zapato = new javax.swing.JRadioButton();
        rad_objeto = new javax.swing.JRadioButton();
        tf_color = new javax.swing.JTextField();
        tf_descripcion = new javax.swing.JTextField();
        tf_marca = new javax.swing.JTextField();
        tf_tamaño = new javax.swing.JTextField();
        tf_calidad = new javax.swing.JTextField();
        tf_precio = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        comb_objetos = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        tf_color1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tf_descripcion1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        tf_marca1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        tf_tamaño1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        tf_calidad1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        tf_precio1 = new javax.swing.JTextField();
        rad_ropa1 = new javax.swing.JRadioButton();
        rad_zapato1 = new javax.swing.JRadioButton();
        rad_objeto1 = new javax.swing.JRadioButton();
        comb_dueño1 = new javax.swing.JComboBox<>();
        bot_modificarobjeto = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        cb_objetos = new javax.swing.JComboBox<>();
        botonobjetoseliminar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        comb_personas_mensaje = new javax.swing.JComboBox<>();
        boton_enviarmensaje = new javax.swing.JButton();
        Mensaje_caja = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel33.setText("Log in");

        jLabel34.setText("Nombre");

        jLabel35.setText("Contraseña");

        boton_entrar.setText("Entrar");
        boton_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_entrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel34))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombre_login, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(contra_login)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(boton_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(490, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(nombre_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(contra_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(boton_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
        );

        jTabbedPane1.addTab("Log in", jPanel7);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setText("Personas");

        jLabel2.setText("Nombre");

        jLabel3.setText("Edad");

        jLabel4.setText("ID");

        jLabel5.setText("Sexo");

        jLabel6.setText("Estado Civil");

        tf_estadocivil.setText("  ");

        jLabel7.setText("Familiar o Cliente");

        jButton3.setText("Agregar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel9.setText("Tipo persona");

        rb_familiar.setText("Familiar");
        rb_familiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_familiarActionPerformed(evt);
            }
        });

        rb_personal.setText("Personal");

        jLabel36.setText("Contraseña");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_sexo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_familiar)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_estadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rb_personal)
                        .addGap(650, 650, 650))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(402, 402, 402))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_estadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_familiar)
                    .addComponent(rb_personal))
                .addGap(120, 120, 120)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Agregar persona", jPanel1);

        cob_personas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cob_personasItemStateChanged(evt);
            }
        });

        jLabel10.setText("Modificar personas");

        jLabel11.setText("Nombre");

        jLabel12.setText("Edad");

        jLabel13.setText("ID");

        jLabel14.setText("Sexo");

        jLabel15.setText("Estado Civil");

        tf_estadocivil1.setText("  ");

        rb_familiar1.setText("Familiar");

        rb_personal1.setText("Personal");

        jLabel16.setText("Tipo persona");

        jLabel17.setText("Familiar o Cliente");

        bot_modificar.setText("Modificar");
        bot_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bot_modificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(cob_personas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_estadocivil1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tf_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(tf_sexo1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(tf_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(47, 47, 47))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16))
                                .addGap(54, 54, 54))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(rb_familiar1)
                                .addGap(27, 27, 27)
                                .addComponent(rb_personal1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(bot_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(476, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cob_personas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(tf_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_estadocivil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_personal1)
                    .addComponent(rb_familiar1))
                .addGap(52, 52, 52)
                .addComponent(bot_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("Modificar Personas", jPanel2);

        tabla_personas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Estado Civil"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_personas);

        cob_eliminar.setText("Eliminar");
        cob_eliminar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cob_eliminarItemStateChanged(evt);
            }
        });
        cob_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cob_eliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(cb_personas2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(cob_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(cb_personas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(cob_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar Persona", jPanel3);

        jLabel18.setText("Objetos");

        jLabel19.setText("Color");

        jLabel20.setText("Descripcion");

        jLabel21.setText("Marca");

        jLabel22.setText("tamaño");

        jLabel23.setText("Calidad");

        jLabel24.setText("Precio");

        jLabel25.setText("Dueño");

        bt_agregarobjeto.setText("Agregar");
        bt_agregarobjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarobjetoMouseClicked(evt);
            }
        });

        rad_ropa.setText("Ropa");

        rad_zapato.setText("Zapato");

        rad_objeto.setText("Objeto Hogar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jLabel18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel21)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(85, 85, 85)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(tf_calidad)
                                                .addGap(17, 17, 17))))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(tf_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel24))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel25))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(comb_dueño, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(bt_agregarobjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(rad_ropa)
                        .addGap(18, 18, 18)
                        .addComponent(rad_zapato)
                        .addGap(18, 18, 18)
                        .addComponent(rad_objeto))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20))
                            .addGap(63, 63, 63)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_color, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                .addComponent(tf_descripcion)))))
                .addContainerGap(452, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel18)
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(tf_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(tf_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel21))
                    .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tf_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tf_calidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comb_dueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rad_ropa)
                    .addComponent(rad_zapato)
                    .addComponent(rad_objeto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(bt_agregarobjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        jTabbedPane1.addTab("Agregar objetos", jPanel4);

        jLabel26.setText("Color");

        jLabel27.setText("Descripcion");

        jLabel28.setText("Marca");

        jLabel29.setText("tamaño");

        jLabel30.setText("Calidad");

        jLabel31.setText("Precio");

        rad_ropa1.setText("Ropa");

        rad_zapato1.setText("Zapato");

        rad_objeto1.setText("Objeto Hogar");

        bot_modificarobjeto.setText("Modificar");
        bot_modificarobjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bot_modificarobjetoMouseClicked(evt);
            }
        });

        jLabel32.setText("Dueño");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(comb_objetos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel30)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel29)
                                                .addComponent(jLabel28)))
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(85, 85, 85)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(tf_precio1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(tf_calidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(17, 17, 17))))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(71, 71, 71)
                                                .addComponent(tf_tamaño1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel31))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(comb_dueño1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(rad_ropa1)
                                .addGap(18, 18, 18)
                                .addComponent(rad_zapato1)
                                .addGap(18, 18, 18)
                                .addComponent(rad_objeto1))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tf_marca1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel26)
                                        .addComponent(jLabel27))
                                    .addGap(63, 63, 63)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_color1)
                                        .addComponent(tf_descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(bot_modificarobjeto))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel32)))
                .addContainerGap(537, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(comb_objetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(tf_color1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(tf_descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel28))
                    .addComponent(tf_marca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(tf_tamaño1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tf_calidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(tf_precio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addGap(2, 2, 2)
                .addComponent(comb_dueño1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rad_ropa1)
                    .addComponent(rad_zapato1)
                    .addComponent(rad_objeto1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(bot_modificarobjeto)
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Modificar objetos", jPanel5);

        botonobjetoseliminar.setText("Eliminar");
        botonobjetoseliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonobjetoseliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(cb_objetos, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(botonobjetoseliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(481, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(cb_objetos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208)
                .addComponent(botonobjetoseliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar objetos", jPanel6);

        boton_enviarmensaje.setText("Enviar mensaje");
        boton_enviarmensaje.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boton_enviarmensajeItemStateChanged(evt);
            }
        });
        boton_enviarmensaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_enviarmensajeMouseClicked(evt);
            }
        });

        jLabel8.setText("Sus mensajes");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(boton_enviarmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(comb_personas_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409, Short.MAX_VALUE)
                        .addComponent(Mensaje_caja, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addGap(136, 136, 136))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comb_personas_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mensaje_caja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(143, 143, 143)
                .addComponent(boton_enviarmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mensajes", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        String Nombre, Edad, ID, Sexo, Estado_civil;
        try {
            Nombre = tf_nombre.getText();
            Edad = tf_edad.getText();
            ID = tf_id.getText();
            Sexo = tf_sexo.getText();
            Estado_civil = tf_estadocivil.getText();

            if (rb_familiar.isSelected()) {
                String rol, trabajo, altura, peso;
                Familiares p = new Familiares();
                p.setNombre(Nombre);
                p.setSexo(Sexo);
                p.setID(ID);
                p.setEdad(Edad);
                p.setEstado_civil(Estado_civil);

                rol = JOptionPane.showInputDialog(null, "Ingrese rol");
                trabajo = JOptionPane.showInputDialog(null, "Ingrese trabajo");
                altura = JOptionPane.showInputDialog(null, "Ingrese altura");
                peso = JOptionPane.showInputDialog(null, "Ingrese peso");

                DefaultComboBoxModel modelo = (DefaultComboBoxModel) cob_personas.getModel();
                modelo.addElement(p);
                cob_personas.setModel(modelo);
                cb_personas2.setModel(modelo);
                comb_dueño.setModel(modelo);
                comb_dueño1.setModel(modelo);
                comb_personas_mensaje.setModel(modelo);
                list.add(p);
                
                
                if(rol.equals("Madre")){
                    contmadre++;
                }else if(rol.equals("Esposo")){
                    
                    contesposo++;
                }else if(rol.equals("Padre")){
                    padre++;
                }else if(rol.equals("Hermana")){
                    hermana++;
                }else if(rol.equals("Hermano")){
                    hermano++;
                }
                
                
                if(hermano==2){
                    JOptionPane.showMessageDialog(this, "YA no mas de este tipo");
                }else if( hermana==5){
                    JOptionPane.showMessageDialog(this, "YA no mas de este tipo");
                }else if(contesposo==2){
                    JOptionPane.showMessageDialog(this, "YA no mas de este tipo");
                }else if(padre==2){
                    JOptionPane.showMessageDialog(this, "YA no mas de este tipo");
                }else if(contmadre==2){
                    JOptionPane.showMessageDialog(this, "YA no mas de este tipo");
                }
                
                
                
                
//int contmadre=0,contesposo=0,padre=0,hermana=0,hermano=0;
            } else if (rb_personal.isSelected()) {

                Personal pe = new Personal();
                String ocupacion_casa, horario_trabajo, tiempo_trabajando, sueldo;

                pe.setNombre(Nombre);
                pe.setSexo(Sexo);
                pe.setID(ID);
                pe.setEdad(Edad);
                pe.setEstado_civil(Estado_civil);

                ocupacion_casa = JOptionPane.showInputDialog(null, "Ingrese ocupacion casa");
                horario_trabajo = JOptionPane.showInputDialog(null, "Ingrese horario trabajo");
                tiempo_trabajando = JOptionPane.showInputDialog(null, "Ingrese tiempo trabajando");
                sueldo = JOptionPane.showInputDialog(null, "Sueldo");
                DefaultComboBoxModel modelo = (DefaultComboBoxModel) cob_personas.getModel();
                modelo.addElement(pe);
                cob_personas.setModel(modelo);
                cb_personas2.setModel(modelo);
                comb_dueño.setModel(modelo);
                comb_dueño1.setModel(modelo);
                comb_personas_mensaje.setModel(modelo);
                list.add(pe);
                //if ()
                

            }

            //Reiniciar
            tf_nombre.setText("");
            tf_sexo.setText("");
            tf_edad.setText("");
            tf_id.setText("");
            tf_estadocivil.setText("");

            JOptionPane.showMessageDialog(this, "HA sido guardado con exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error");
        }


    }//GEN-LAST:event_jButton3MouseClicked

    private void bot_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot_modificarMouseClicked
        // TODO add your handling code here:
        selec = (Persona) cob_personas.getSelectedItem();

        selec.setNombre(tf_nombre1.getText());
        selec.setEdad(tf_edad1.getText());
        selec.setID(tf_id1.getText());
        selec.setEstado_civil(tf_estadocivil1.getText());
        selec.setSexo(tf_sexo1.getText());

        if (rb_familiar.isSelected()) {
            String rol, trabajo, altura, peso;

            rol = JOptionPane.showInputDialog(null, "Ingrese rol");
            trabajo = JOptionPane.showInputDialog(null, "Ingrese trabajo");
            altura = JOptionPane.showInputDialog(null, "Ingrese altura");
            peso = JOptionPane.showInputDialog(null, "Ingrese peso");

            ((Familiares) selec).setAltura(altura);
            ((Familiares) selec).setTrabajo(trabajo);
            ((Familiares) selec).setAltura(altura);
            ((Familiares) selec).setPeso(peso);

        } else if (rb_personal.isSelected()) {

            String ocupacion_casa, horario_trabajo, tiempo_trabajando, sueldo;

            ocupacion_casa = JOptionPane.showInputDialog(null, "Ingrese ocupacion casa");
            horario_trabajo = JOptionPane.showInputDialog(null, "Ingrese horario trabajo");
            tiempo_trabajando = JOptionPane.showInputDialog(null, "Ingrese tiempo trabajando");
            sueldo = JOptionPane.showInputDialog(null, "Sueldo");

            ((Personal) selec).setHorario_trabajo(horario_trabajo);
            ((Personal) selec).setSueldo(sueldo);
            ((Personal) selec).setOcupacion_casa(ocupacion_casa);
            ((Personal) selec).setTiempo_trabajando(tiempo_trabajando);

        }
        JOptionPane.showMessageDialog(null, "Se modifico con exito");


    }//GEN-LAST:event_bot_modificarMouseClicked

    private void cob_personasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cob_personasItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == 2) {
            selec = (Persona) cb_personas2.getSelectedItem();
            //Agregar un arreglo de object
            Object[] newrow = {
                selec.getNombre(),
                selec.getEstado_civil(),};

            DefaultTableModel modelo = (DefaultTableModel) tabla_personas.getModel();
            modelo.addRow(newrow);
            tabla_personas.setModel(modelo);

        }


    }//GEN-LAST:event_cob_personasItemStateChanged

    private void cob_eliminarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cob_eliminarItemStateChanged
        // TODO add your handling code here:


    }//GEN-LAST:event_cob_eliminarItemStateChanged

    private void cob_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cob_eliminarMouseClicked
        // TODO add your handling code here:

        DefaultComboBoxModel modeloc = (DefaultComboBoxModel) cob_personas.getModel();

        modeloc.removeElementAt(cob_personas.getSelectedIndex());

        cob_personas.setModel(modeloc);
        cb_personas2.setModel(modeloc);
        comb_dueño.setModel(modeloc);
        comb_dueño1.setModel(modeloc);
        comb_personas_mensaje.setModel(modeloc);

    }//GEN-LAST:event_cob_eliminarMouseClicked

    private void bt_agregarobjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarobjetoMouseClicked
        // TODO add your handling code here:
        String color, descripcion, marca, tamaño, calidad, precio;
        Object dueño;
        color = tf_color.getText();
        descripcion = tf_descripcion.getText();
        marca = tf_marca.getText();
        tamaño = tf_tamaño.getText();
        calidad = tf_calidad.getText();
        precio = tf_precio.getText();
        dueño = comb_dueño.getSelectedItem();

        if (rad_objeto.isSelected()) {
            String tiempo_vida, area_casa, instrucciones_armado, fecha_compra;
            tiempo_vida = JOptionPane.showInputDialog(null, "Tiempo de vida");
            area_casa = JOptionPane.showInputDialog(null, "Area de la casa");

            ObjetoHogar o = new ObjetoHogar();
            o.setMarca(marca);
            o.setColor(color);
            o.setDescripción(descripcion);
            o.setMarca(marca);
            o.setTamaño(tamaño);
            o.setDueño(dueño);

            DefaultComboBoxModel modelor = (DefaultComboBoxModel) comb_objetos.getModel();
            modelor.addElement(o);
            comb_objetos.setModel(modelor);
            cb_objetos.setModel(modelor);

        } else if (rad_ropa.isSelected()) {
            String talla, material, pais_elaboracion;

            talla = JOptionPane.showInputDialog(null, "Talla");
            material = JOptionPane.showInputDialog(null, "Material");

            Ropa r = new Ropa();

            r.setMarca(marca);
            r.setColor(color);
            r.setDescripción(descripcion);
            r.setMarca(marca);
            r.setTamaño(tamaño);
            r.setDueño(dueño);
            DefaultComboBoxModel modelor = (DefaultComboBoxModel) comb_objetos.getModel();
            modelor.addElement(r);
            comb_objetos.setModel(modelor);
            cb_objetos.setModel(modelor);

        } else if (rad_zapato.isSelected()) {

            String talla, suela, confort;

            Zapato z = new Zapato();
            z.setMarca(marca);
            z.setColor(color);
            z.setDescripción(descripcion);
            z.setMarca(marca);
            z.setTamaño(tamaño);
            z.setDueño(dueño);
            DefaultComboBoxModel modelor = (DefaultComboBoxModel) comb_objetos.getModel();
            modelor.addElement(z);
            comb_objetos.setModel(modelor);
            cb_objetos.setModel(modelor);

        }
        JOptionPane.showMessageDialog(this, "ha sido guardao con exito");


    }//GEN-LAST:event_bt_agregarobjetoMouseClicked

    private void bot_modificarobjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot_modificarobjetoMouseClicked
        // TODO add your handling code here:

        se = (Objetos) comb_objetos.getSelectedItem();

        se.setMarca(tf_marca1.getText());
        se.setColor(tf_color1.getText());
        se.setDescripción(tf_descripcion1.getText());

        se.setTamaño(tf_tamaño1.getText());

        se.setDueño(comb_dueño.getSelectedItem());

        if (rad_objeto.isSelected()) {
            String tiempo_vida, area_casa, instrucciones_armado, fecha_compra;
            tiempo_vida = JOptionPane.showInputDialog(null, "Tiempo de vida");
            area_casa = JOptionPane.showInputDialog(null, "Area de la casa");

        } else if (rad_ropa.isSelected()) {
            String talla, material, pais_elaboracion;

            talla = JOptionPane.showInputDialog(null, "Talla");
            material = JOptionPane.showInputDialog(null, "Material");

        } else if (rad_zapato.isSelected()) {

            String talla, suela, confort;

            talla = JOptionPane.showInputDialog(null, "Talla");

        }

        JOptionPane.showMessageDialog(this, "Ha sido modificado");
    }//GEN-LAST:event_bot_modificarobjetoMouseClicked

    private void botonobjetoseliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonobjetoseliminarMouseClicked
        // TODO add your handling code here:
        DefaultComboBoxModel modeloc = (DefaultComboBoxModel) cb_objetos.getModel();

        modeloc.removeElementAt(cb_objetos.getSelectedIndex());

        cb_objetos.setModel(modeloc);
        comb_objetos.setModel(modeloc);


    }//GEN-LAST:event_botonobjetoseliminarMouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:

        if (jTabbedPane1.getSelectedIndex() != 0 && jTabbedPane1.getSelectedIndex() != 7) {
            if (nombre.equals("kim") && contraseñau.equals("kimk")) {
                JOptionPane.showMessageDialog(null, "Bienvenida Kim");
            } else {
                JOptionPane.showMessageDialog(this, "No es el administrador");
                jTabbedPane1.setSelectedIndex(0);
            }

        }

        /*if (jTabbedPane1.getSelectedIndex() != 0 && (!nombre_login.getText().equals("kim") && !contra_login.getText().equals("kimk"))) {

            if (jTabbedPane1.getSelectedIndex() == 1) {
                JOptionPane.showInputDialog("Bienvenido");
            } else {
                JOptionPane.showMessageDialog(this, "No es el administrador");
                jTabbedPane1.setSelectedIndex(0);
            }

        }*/

    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void rb_familiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_familiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_familiarActionPerformed

    private void boton_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_entrarMouseClicked
        // TODO add your handling code here:
        nombre = nombre_login.getText();
        contraseñau = contra_login.getText();
        boolean aux = false;

        for (Persona t : list) {
            if (nombre.equals(t.getNombre())) {

                aux = true;
                break;

            }
        }

        if (aux = false) {
            JOptionPane.showMessageDialog(this, "No existe el usuario");
        }

        jTabbedPane1.setSelectedIndex(7);


    }//GEN-LAST:event_boton_entrarMouseClicked

    private void boton_enviarmensajeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boton_enviarmensajeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_enviarmensajeItemStateChanged

    private void boton_enviarmensajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_enviarmensajeMouseClicked
        // TODO add your handling code here:
        String mensaje = JOptionPane.showInputDialog(this, "Enviar un mensaje");

        selec = (Persona) comb_personas_mensaje.getSelectedItem();

        //if (((Familiares) selec).getRol().equals("Esposo") || ((Familiares) selec).getRol().equals("esposo")) {
        JOptionPane.showMessageDialog(this, "Cifrado de cesar");
        int codigo = Integer.parseInt(JOptionPane.showInputDialog(this, "Escribir codigo"));
        String texto = mensaje;
        String cesar = cifradoCesar(texto, codigo);
        JOptionPane.showMessageDialog(this, "Cifrado de cesar: " + cesar);
       String transposicion= CifradoTransposicion(cesar);
        JOptionPane.showMessageDialog(this, "Cifrado de transposicion:  " + transposicion);
        
        String codigo2 = JOptionPane.showInputDialog(this, "Escribir codigo");
        Vigenere v = new Vigenere(transposicion,codigo2);
        String vigenere= v.Cifrar();
        JOptionPane.showMessageDialog(this, "Vigenere:  "+vigenere);
        
        //Descifrar
        String devolver3= v.DesCifrar();
        String devolver2=CifradoTransposicion(devolver3);
        String devolver1= descifradoCesar(devolver2,codigo);
        
        JOptionPane.showMessageDialog(this, "Fin del mensaje: "+mensaje);
        

        // } else {
        selec.getListam().add(mensaje);
        //}

        DefaultComboBoxModel modelor = (DefaultComboBoxModel) Mensaje_caja.getModel();
        modelor.addElement(mensaje);
        Mensaje_caja.setModel(modelor);


    }//GEN-LAST:event_boton_enviarmensajeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_Examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_Examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_Examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_Examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_Examen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Mensaje_caja;
    private javax.swing.JButton bot_modificar;
    private javax.swing.JButton bot_modificarobjeto;
    private javax.swing.JButton boton_entrar;
    private javax.swing.JButton boton_enviarmensaje;
    private javax.swing.JButton botonobjetoseliminar;
    private javax.swing.JButton bt_agregarobjeto;
    private javax.swing.JComboBox<String> cb_objetos;
    private javax.swing.JComboBox<String> cb_personas2;
    private javax.swing.JButton cob_eliminar;
    private javax.swing.JComboBox<String> cob_personas;
    private javax.swing.JComboBox<String> comb_dueño;
    private javax.swing.JComboBox<String> comb_dueño1;
    private javax.swing.JComboBox<String> comb_objetos;
    private javax.swing.JComboBox<String> comb_personas_mensaje;
    private javax.swing.JTextField contra_login;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nombre_login;
    private javax.swing.JRadioButton rad_objeto;
    private javax.swing.JRadioButton rad_objeto1;
    private javax.swing.JRadioButton rad_ropa;
    private javax.swing.JRadioButton rad_ropa1;
    private javax.swing.JRadioButton rad_zapato;
    private javax.swing.JRadioButton rad_zapato1;
    private javax.swing.JRadioButton rb_familiar;
    private javax.swing.JRadioButton rb_familiar1;
    private javax.swing.JRadioButton rb_personal;
    private javax.swing.JRadioButton rb_personal1;
    private javax.swing.JTable tabla_personas;
    private javax.swing.JTextField tf_calidad;
    private javax.swing.JTextField tf_calidad1;
    private javax.swing.JTextField tf_color;
    private javax.swing.JTextField tf_color1;
    private javax.swing.JTextField tf_contraseña;
    private javax.swing.JTextField tf_descripcion;
    private javax.swing.JTextField tf_descripcion1;
    private javax.swing.JTextField tf_edad;
    private javax.swing.JTextField tf_edad1;
    private javax.swing.JTextField tf_estadocivil;
    private javax.swing.JTextField tf_estadocivil1;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_id1;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_marca1;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_precio1;
    private javax.swing.JTextField tf_sexo;
    private javax.swing.JTextField tf_sexo1;
    private javax.swing.JTextField tf_tamaño;
    private javax.swing.JTextField tf_tamaño1;
    // End of variables declaration//GEN-END:variables
Persona selec = new Persona();
    Objetos se = new Objetos();
    ArrayList<Persona> list = new ArrayList();

    String nombre, contraseñau;

    public static String cifradoCesar(String texto, int codigo) {
        StringBuilder cifrado = new StringBuilder();
        codigo = codigo % 26;
        for (int i = 0; i < texto.length(); i++) {
            if (texto.charAt(i) >= 'a' && texto.charAt(i) <= 'z') {
                if ((texto.charAt(i) + codigo) > 'z') {
                    cifrado.append((char) (texto.charAt(i) + codigo - 26));
                } else {
                    cifrado.append((char) (texto.charAt(i) + codigo));
                }
            } else if (texto.charAt(i) >= 'A' && texto.charAt(i) <= 'Z') {
                if ((texto.charAt(i) + codigo) > 'Z') {
                    cifrado.append((char) (texto.charAt(i) + codigo - 26));
                } else {
                    cifrado.append((char) (texto.charAt(i) + codigo));
                }
            }
        }
        return cifrado.toString();
    }

    //Transposiocikn simple
    public String CifradoTransposicion(String mensaje) {

        char arr[] = mensaje.toCharArray();
        String cripto = "";
        mensaje = "";
    
         
        for (int i = 0; i < arr.length; i++) {
            if (arr[i] != ' ') {
                mensaje += arr[i];
            }
        }

        arr = null;

        arr = mensaje.toCharArray();

        int count = arr.length; 

        while (count != 0) {
            cripto += (arr[count - 1]);
            count = count - 1;
        }

        return cripto;
    }
    
    
    
    
    
    
   //////////////////////
    public static String descifradoCesar(String texto, int codigo) {
        StringBuilder cifrado = new StringBuilder();
        codigo = codigo % 26;
        for (int i = 0; i < texto.length(); i++) {
            if (texto.charAt(i) >= 'a' && texto.charAt(i) <= 'z') {
                if ((texto.charAt(i) - codigo) < 'a') {
                    cifrado.append((char) (texto.charAt(i) - codigo + 26));
                } else {
                    cifrado.append((char) (texto.charAt(i) - codigo));
                }
            } else if (texto.charAt(i) >= 'A' && texto.charAt(i) <= 'Z') {
                if ((texto.charAt(i) - codigo) < 'A') {
                    cifrado.append((char) (texto.charAt(i) - codigo + 26));
                } else {
                    cifrado.append((char) (texto.charAt(i) - codigo));
                }
            }
        }
        return cifrado.toString();
    
    }
    
    
    
    int contmadre=0,contesposo=0,padre=0,hermana=0,hermano=0;

}//Fin clase
