/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClasesProyecto;

import static labproyecto_martinperez.LabProyecto_MartinPerez.Tableroinicial;

/**
 *
 * @author mjper
 */
public class Fondo extends javax.swing.JFrame {

    /**
     * Creates new form Fondo
     */
    public Fondo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Boton_iniciar = new javax.swing.JButton();
        Boton_cerrar = new javax.swing.JButton();
        Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Stencil", 2, 48)); // NOI18N
        Titulo.setText("AJEDREZ ");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 430, -1));

        Boton_iniciar.setBackground(new java.awt.Color(0, 0, 0));
        Boton_iniciar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        Boton_iniciar.setForeground(new java.awt.Color(255, 255, 255));
        Boton_iniciar.setText("INICIAR PARTIDA");
        Boton_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_iniciarActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 320, 70));

        Boton_cerrar.setText("jButton2");
        getContentPane().add(Boton_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 450, 100, 40));

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/original.jpg"))); // NOI18N
        Imagen.setText("jLabel1");
        getContentPane().add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_iniciarActionPerformed
       Tablero tab = new Tablero(Tableroinicial());
       
    }//GEN-LAST:event_Boton_iniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fondo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fondo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fondo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fondo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fondo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_cerrar;
    private javax.swing.JButton Boton_iniciar;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
